data=read.table(file.choose(),sep = ";", header = TRUE, na.strings = "?")
data$Date <- as.Date(data$Date,format="%d/%m/%Y")
data <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
hist(data$Global_active_power, col="red",main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.copy(png, file="plot1.png")
dev.off()
