temp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",temp)
data <- read.table(unz(temp, "household_power_consumption.txt"),sep = ";", header = TRUE, na.strings = "?")
unlink(temp)

#data=read.table(file.choose(),sep = ";", header = TRUE, na.strings = "?")

data$Date <- as.Date(data$Date,format="%d/%m/%Y")
data <- subset(data, Date >= "2007-02-01" & Date <= "2007-02-02")
data$datetime <- as.POSIXct(paste(data$Date, data$Time))
par(mfrow=c(2,2), mar=c(4,4,2,2),mgp=c(2.5,1,0))
Sys.setlocale("LC_TIME", "C")
plot(data$datetime,data$Global_active_power,type="l", ylab="Global Active Power",xlab="",cex.lab=0.95, cex.axis=0.95)
plot(data$datetime,data$Voltage,type="l", ylab="Voltage",xlab="datetime",cex.lab=0.95, cex.axis=0.95)
plot(data$datetime,data$Sub_metering_1,type="l", ylab="Energy sub metering",xlab="",cex.lab=0.95, cex.axis=0.95)
lines(data$datetime,data$Sub_metering_2, col="red")
lines(data$datetime,data$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black","red", "blue"), legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), cex=0.85, bty = "n",xjust = 1,inset = c(-0.15, -0.05),seg.len = c(1,1,1),x.intersp = 0.5, y.intersp = 0.8)
plot(data$datetime,data$Global_reactive_power,type="l", ylab="Global_reactive_power",xlab="datetime",cex.lab=0.95, cex.axis=0.95)
dev.copy(png, file="plot4.png")
dev.off()
